### ISSUE TITLE
Reel: Modify Reel texture to show white background

### ISSUE THREAD

**Issue by aleemulhaq** [aleemulhaq/BlenderModels#8]
Currently Reel cylinders have a black background.

We want this to be changed to a white background, so that the reel matches well in contrast with the Slot Machine body(black frame).

Note: The side faces of the reel can be same colour(white) as the background.

**Comment by CosmanAgraz** [comment]
![image](https://user-images.githubusercontent.com/9828407/76810092-414bed00-67c3-11ea-89df-c03db7d5a56d.png)

You can change shading from "smooth" to "flat" where the picture is shown.
